import Chess.SemanticRespectsGeometryLemmas
import Chess.Completeness
import Chess.SemanticMoveFlagLemmas
import Chess.SemanticCaptureFlagLemmas
import Chess.SemanticNonCastleRookFieldLemmas
import Chess.SemanticPromotionSoundnessLemmas
import Chess.SemanticFideLegalSoundness
import Chess.StateInvariants
import Chess.SemanticBasicLegalLemmas
import Chess.SemanticPieceTargetsCompletenessLemmas
import Chess.SemanticPawnPieceTargetsCompletenessLemmas
import Chess.SemanticCastlingPieceTargetsCompletenessLemmas
import Chess.SemanticPinFilterLemmas
import Chess.SemanticFideLegalEquivalence
import Chess.SemanticFideLegalEquivalenceReachable
import Chess.SlidingTargetsCompletenessHelpers
import Chess.SlidingTargetsDeltaLemmas

open Chess Chess.Rules

-- Verify the dispatcher lemma type-checks and is accessible.

#check respectsGeometry_of_pieceTargets

#check allLegalMoves_sound_respectsGeometry

#check mem_allLegalMoves_isEnPassant_implies_pawn
#check mem_allLegalMoves_isCastle_implies_king

#check allLegalMoves_sound_captureFlagConsistentWithEP

#check mem_allLegalMoves_nonCastle_rookFields_none

#check mem_allLegalMoves_promotion_isSome_implies_pawn_and_rank
#check mem_allLegalMoves_pawn_toPromotionRank_implies_promotion_isSome

#check allLegalMoves_sound_fideLegalSemantic
#check allLegalMoves_sound_fideLegalSemantic_of_reachable

#check mem_allLegalMoves_pawn_toPromotionRank_implies_promotion_isSome_of_reachable

#check fideLegalSemantic_implies_basicLegalAndSafe

#check fideLegalSemantic_implies_mem_pieceTargets_knight
#check fideLegalSemantic_implies_mem_pieceTargets_king_not_castle
#check fideLegalSemantic_implies_mem_pieceTargets_rook
#check fideLegalSemantic_implies_mem_pieceTargets_bishop
#check fideLegalSemantic_implies_mem_pieceTargets_queen
#check fideLegalSemantic_implies_mem_pieceTargets_pawn
#check fideLegalSemantic_implies_mem_pieceTargets_king_castle
#check fideLegalSemantic_implies_respectsPin_of_not_knight
#check fideLegalSemantic_implies_mem_allLegalMoves_of_not_knight
#check fideLegalSemantic_implies_respectsPin
#check fideLegalSemantic_implies_mem_allLegalMoves
#check fideLegalSemantic_iff_mem_allLegalMoves
#check fideLegalSemantic_iff_fideLegal
#check fideLegalSemantic_iff_mem_allLegalMoves_of_reachable
#check fideLegalSemantic_iff_fideLegal_of_reachable

#check slidingTargets_walk_acc_subset
#check slidingTargets_walk_mem_of_empty_square
#check slidingTargets_walk_mem_of_enemy_square

#check Chess.Movement.signInt_mul_natAbs
#check Chess.Movement.squareFromInts_rookDelta_rookOffset
#check Chess.Movement.squareFromInts_bishopDelta_bishopOffset
#check Chess.Movement.squareFromInts_rookDelta_step_some
#check Chess.Movement.rookDelta_mem_rookDeltas
#check Chess.Movement.rook_step_square_mem_squaresBetween

#check mem_pawn_pieceTargets_promotion_eq_some_implies_mem_promotionTargets
